# Generated by Django 5.2.1 on 2025-06-11 12:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rivewratting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RivewRatting',
            new_name='ReviewRating',
        ),
    ]
